Allow configuration of validation path
marceldegraaf/ueberauth_cas pull request #9
Opened 2020-10-08 12:51 UTC by yannvery

Allow to configure validation path to be able to use the strategy with a CAS server that uses CAS 3.0 specifications.

I didn't find a real difference between CAS 2.0 and CAS 3.0 validation but the validation path.
[/p3/serviceValidate [CAS 3.0]](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#head2.8).
I've tested the validation with a real CAS 3.0 server without any issue.

I didn't find a way to properly test the modification since the `service_url` function is a private one. However I'm ready to modify anything that bothers you.

2020-10-08 15:37 UTC, niknetniko requested changes
A miniscule tweak and some small changes to the docs, but looks good otherwise 👍

2020-10-08 15:37 UTC, niknetniko commented on lib/ueberauth/strategy/cas.ex
> +       validation_path: "/serviceValidate"
```suggestion
       validation_path: "/serviceValidate",
```

2020-10-08 15:37 UTC, niknetniko commented on lib/ueberauth/strategy/cas.ex
> +    The validation path can be overrided via configuration to comply with
```suggestion
    The validation path can be overridden via configuration to comply with
```

2020-10-08 15:37 UTC, niknetniko commented on lib/ueberauth/strategy/cas.ex
> +    CAS 3.0 specifications and use `/p3/serviceValidate`.
```suggestion
    CAS 3.0 and use `/p3/serviceValidate`.
```

2020-10-08 16:58 UTC, yannvery commented
Thanks for your feedbacks.

2020-10-09 11:43 UTC, niknetniko approved these changes

2020-10-09 11:43 UTC, merged